package com.garcia.hibernateuser.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

//add table 
@Entity
@Table(name = "users")
public class User {
// created a Pojo class
	@Column(name ="user_id")
	
	//2. final annotation change the column name from the table.. we want to specify the column name
	//1. we want to set id as the primary id
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private String fullName;
	private String Email;
	private int age;
	private double salary;
	private String city;
	
	//create an empty constructor.
	
	public User() {}

	public User(String fullName, String email, int age, double salary, String city) {
		//then create a constructor with parameters minus id as it will be auto generated by using the source 
		super();
		this.fullName = fullName;
		Email = email;
		this.age = age;
		this.salary = salary;
		this.city = city;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getEmail() {
		return Email;
	}

	public void setEmail(String email) {
		Email = email;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public double getSalary() {
		return salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	// this displays the values for the current object

	@Override
	public String toString() {
		return "User [id=" + id + ", fullName=" + fullName + ", Email=" + Email + ", age=" + age + ", salary=" + salary
				+ ", city=" + city + "]";
	};
}
